/*
 * This file is generated by jOOQ.
 */
package com.money.model;


import com.money.model.tables.Account;
import com.money.model.tables.Transfer;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MoneyTransfer extends SchemaImpl {

    private static final long serialVersionUID = 1890305173;

    /**
     * The reference instance of <code>MONEY_TRANSFER</code>
     */
    public static final MoneyTransfer MONEY_TRANSFER = new MoneyTransfer();

    /**
     * The table <code>MONEY_TRANSFER.ACCOUNT</code>.
     */
    public final Account ACCOUNT = com.money.model.tables.Account.ACCOUNT;

    /**
     * The table <code>MONEY_TRANSFER.TRANSFER</code>.
     */
    public final Transfer TRANSFER = com.money.model.tables.Transfer.TRANSFER;

    /**
     * No further instances allowed
     */
    private MoneyTransfer() {
        super("MONEY_TRANSFER", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Account.ACCOUNT,
            Transfer.TRANSFER);
    }
}
