/*
 * This file is generated by jOOQ.
 */
package com.money.model;


import com.money.model.tables.Account;
import com.money.model.tables.Transfer;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in MONEY_TRANSFER
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>MONEY_TRANSFER.ACCOUNT</code>.
     */
    public static final Account ACCOUNT = Account.ACCOUNT;

    /**
     * The table <code>MONEY_TRANSFER.TRANSFER</code>.
     */
    public static final Transfer TRANSFER = Transfer.TRANSFER;
}
