/*
 * This file is generated by jOOQ.
 */
package com.money.model.tables.records;


import com.money.model.tables.Transfer;

import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TransferRecord extends UpdatableRecordImpl<TransferRecord> implements Record7<Long, Long, Long, BigDecimal, String, Timestamp, Integer> {

    private static final long serialVersionUID = -455953988;

    /**
     * Setter for <code>MONEY_TRANSFER.TRANSFER.ID</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>MONEY_TRANSFER.TRANSFER.ID</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>MONEY_TRANSFER.TRANSFER.TO_ACCOUNT_ID</code>.
     */
    public void setToAccountId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>MONEY_TRANSFER.TRANSFER.TO_ACCOUNT_ID</code>.
     */
    public Long getToAccountId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>MONEY_TRANSFER.TRANSFER.FROM_ACCOUNT_ID</code>.
     */
    public void setFromAccountId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>MONEY_TRANSFER.TRANSFER.FROM_ACCOUNT_ID</code>.
     */
    public Long getFromAccountId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>MONEY_TRANSFER.TRANSFER.AMOUNT</code>.
     */
    public void setAmount(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>MONEY_TRANSFER.TRANSFER.AMOUNT</code>.
     */
    public BigDecimal getAmount() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>MONEY_TRANSFER.TRANSFER.TRANSFER_TYPE</code>.
     */
    public void setTransferType(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>MONEY_TRANSFER.TRANSFER.TRANSFER_TYPE</code>.
     */
    public String getTransferType() {
        return (String) get(4);
    }

    /**
     * Setter for <code>MONEY_TRANSFER.TRANSFER.CREATED_DATE</code>.
     */
    public void setCreatedDate(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>MONEY_TRANSFER.TRANSFER.CREATED_DATE</code>.
     */
    public Timestamp getCreatedDate() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>MONEY_TRANSFER.TRANSFER.REC_VERSION</code>.
     */
    public void setRecVersion(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>MONEY_TRANSFER.TRANSFER.REC_VERSION</code>.
     */
    public Integer getRecVersion() {
        return (Integer) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Long, Long, Long, BigDecimal, String, Timestamp, Integer> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Long, Long, Long, BigDecimal, String, Timestamp, Integer> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Transfer.TRANSFER.ID;
    }

    @Override
    public Field<Long> field2() {
        return Transfer.TRANSFER.TO_ACCOUNT_ID;
    }

    @Override
    public Field<Long> field3() {
        return Transfer.TRANSFER.FROM_ACCOUNT_ID;
    }

    @Override
    public Field<BigDecimal> field4() {
        return Transfer.TRANSFER.AMOUNT;
    }

    @Override
    public Field<String> field5() {
        return Transfer.TRANSFER.TRANSFER_TYPE;
    }

    @Override
    public Field<Timestamp> field6() {
        return Transfer.TRANSFER.CREATED_DATE;
    }

    @Override
    public Field<Integer> field7() {
        return Transfer.TRANSFER.REC_VERSION;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getToAccountId();
    }

    @Override
    public Long component3() {
        return getFromAccountId();
    }

    @Override
    public BigDecimal component4() {
        return getAmount();
    }

    @Override
    public String component5() {
        return getTransferType();
    }

    @Override
    public Timestamp component6() {
        return getCreatedDate();
    }

    @Override
    public Integer component7() {
        return getRecVersion();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getToAccountId();
    }

    @Override
    public Long value3() {
        return getFromAccountId();
    }

    @Override
    public BigDecimal value4() {
        return getAmount();
    }

    @Override
    public String value5() {
        return getTransferType();
    }

    @Override
    public Timestamp value6() {
        return getCreatedDate();
    }

    @Override
    public Integer value7() {
        return getRecVersion();
    }

    @Override
    public TransferRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public TransferRecord value2(Long value) {
        setToAccountId(value);
        return this;
    }

    @Override
    public TransferRecord value3(Long value) {
        setFromAccountId(value);
        return this;
    }

    @Override
    public TransferRecord value4(BigDecimal value) {
        setAmount(value);
        return this;
    }

    @Override
    public TransferRecord value5(String value) {
        setTransferType(value);
        return this;
    }

    @Override
    public TransferRecord value6(Timestamp value) {
        setCreatedDate(value);
        return this;
    }

    @Override
    public TransferRecord value7(Integer value) {
        setRecVersion(value);
        return this;
    }

    @Override
    public TransferRecord values(Long value1, Long value2, Long value3, BigDecimal value4, String value5, Timestamp value6, Integer value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TransferRecord
     */
    public TransferRecord() {
        super(Transfer.TRANSFER);
    }

    /**
     * Create a detached, initialised TransferRecord
     */
    public TransferRecord(Long id, Long toAccountId, Long fromAccountId, BigDecimal amount, String transferType, Timestamp createdDate, Integer recVersion) {
        super(Transfer.TRANSFER);

        set(0, id);
        set(1, toAccountId);
        set(2, fromAccountId);
        set(3, amount);
        set(4, transferType);
        set(5, createdDate);
        set(6, recVersion);
    }
}
